# Generated by Django 4.0.4 on 2022-05-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0002_urlwithshortcut'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlwithshortcut',
            name='url_shortcut',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
    ]
