# Generated by Django 4.0.4 on 2022-05-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0003_urlwithshortcut_url_shortcut'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlwithshortcut',
            name='full_url',
            field=models.URLField(default=''),
        ),
    ]
